/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : bigint,
  'title' : string,
  'duration' : string,
  'description' : string,
  'level' : string,
  'category' : string,
}
export interface Instructor {
  'id' : bigint,
  'bio' : string,
  'title' : string,
  'name' : string,
}
export interface PricingPlan {
  'id' : bigint,
  'features' : Array<string>,
  'name' : string,
  'isPopular' : boolean,
  'billingPeriod' : string,
  'price' : bigint,
}
export interface Submission {
  'name' : string,
  'submittedAt' : Time,
  'email' : string,
  'courseInterest' : string,
  'message' : string,
}
export interface Testimonial {
  'id' : bigint,
  'studentName' : string,
  'quote' : string,
  'courseTaken' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getInstructors' : ActorMethod<[], Array<Instructor>>,
  'getPricingPlans' : ActorMethod<[], Array<PricingPlan>>,
  'getSubmissionById' : ActorMethod<[bigint], Submission>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'submitForm' : ActorMethod<[string, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];