/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Submission = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'courseInterest' : IDL.Text,
  'message' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'description' : IDL.Text,
  'level' : IDL.Text,
  'category' : IDL.Text,
});
export const Instructor = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'name' : IDL.Text,
});
export const PricingPlan = IDL.Record({
  'id' : IDL.Nat,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'isPopular' : IDL.Bool,
  'billingPeriod' : IDL.Text,
  'price' : IDL.Nat,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'studentName' : IDL.Text,
  'quote' : IDL.Text,
  'courseTaken' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
  'getPricingPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
  'getSubmissionById' : IDL.Func([IDL.Nat], [Submission], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'courseInterest' : IDL.Text,
    'message' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'description' : IDL.Text,
    'level' : IDL.Text,
    'category' : IDL.Text,
  });
  const Instructor = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'name' : IDL.Text,
  });
  const PricingPlan = IDL.Record({
    'id' : IDL.Nat,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'isPopular' : IDL.Bool,
    'billingPeriod' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'studentName' : IDL.Text,
    'quote' : IDL.Text,
    'courseTaken' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getInstructors' : IDL.Func([], [IDL.Vec(Instructor)], ['query']),
    'getPricingPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
    'getSubmissionById' : IDL.Func([IDL.Nat], [Submission], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };